### ISSUE TITLE
initial release: waydroid does not find binder

### ISSUE THREAD

**Issue by FrankBS** [sailfish-on-gta4xlwifi/docs#1]
devel-su waydroid init
[10:55:58] ERROR: Binder node "binder" for waydroid not found
[10:55:58] See also: https://github.com/waydroid
Run 'waydroid log' for details.

from waydroid.log
`
 (016660) [10:55:58] ERROR: Binder node "binder" for waydroid not found

 (016660) [10:55:58] See also: <https://github.com/waydroid>

 (016660) [10:55:58] Traceback (most recent call last):

  File "/opt/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/opt/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/opt/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/opt/waydroid/tools/helpers/drivers.py", line 158, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')

 OSError: Binder node "binder" for waydroid not found
`

**Comment by FrankBS** [comment]
tried to change settings in /etc/gbinder.d/anbox-hybris.conf because /dev/binder, /dev/hwbinder and /dev/vndbinder exist, but had still the same error.
